### ISSUE TITLE
Matching defaults between developModel and transform

### ISSUE THREAD

**Issue by gkaguirre** [gkaguirrelab/rgcDisplacementMap#6]
The code makes use of two routines that "develop" the mRGC and mRF linking functions. There are default values in these routines. These default values are used again in the "transform" functions. It can occur, however, that the default values set in the develop and transform functions are different, causing model errors. Need to devise a way to force these to match.

**Comment by DavidBrainard** [comment]
We hit this problem often in the isetbio code base and have not yet developed a general solution.  I am working on approaches, would be interesting to compare notes.

**Comment by gkaguirre** [comment]
Ended up surfacing these parameters to a lower level function that calls both the develop and transform functions.
